scrape_configs:
  - job_name: "apigateway"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.10:8080"]
  - job_name: "productservice"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ "192.168.1.10:8088", "192.168.1.10:8079" ]

#TODO: Add more services and replace the IP addresses with the actual IP addresses of the services.